### ISSUE TITLE
VisualSignature has leading space before SignatureReason

### ISSUE THREAD

**Issue by davidstrahm** [SwisscomTrustServices/pdfbox-ais#6]
When using the VisualSignature feature, there is a leading space of 1.5f before the signature Reason:
![image](https://user-images.githubusercontent.com/16301487/196633826-5a0a9655-002d-451a-a767-35f1e5cd3b23.png)

This is because the leading space is explicitly set at 1.5f in the PdfDocument:
https://github.com/SwisscomTrustServices/pdfbox-ais-client/blob/8d52c759ade267b0c443fcd6f15bc9635c745d72/src/main/java/com/swisscom/ais/client/impl/PdfDocument.java#L408

This leading space should be removed

**Comment by paulmuntean** [comment]
can you please provide more details about this finding?

**Comment by davidstrahm** [comment]
The feature "createVisualSignature" allows setting an image for the signature at specified coordinates. 
I would expect the signatureReason text to be aligned with these coordinates as well. But because there is a leading space of 1.5f hardcoded in PdfDocument.java (see link in previous comment), the signatureReason is indented 1.5f. as seen on my screenshot. It might be possible that if the indentation is 0, the text is cutoff by the signature window. this I have not tested. In this case, an indentation of 0.1f to 0.5f would probably be enough for the text not do be cut off.

**Comment by ionut-vacariu-mindit** [comment]
@davidstrahm  - fiexd. leading of 0.3 is used now.
Thanks

**Comment by davidstrahm** [comment]
@ionut-vacariu-mindit Can you make another release in your local repository?

**Comment by davidstrahm** [comment]
@ionut-vacariu-mindit Any update on this?

**Comment by ionut-vacariu-mindit** [comment]
@davidstrahm - is there any issue with those?
https://github.com/SwisscomTrustServices/pdfbox-ais-client/tree/etsi_integration/repository/com/swisscom/ais/pdfbox-ais/1.3.0

**Comment by davidstrahm** [comment]
Thanks, I didn't realize they are now on a branch
