### ISSUE TITLE
AIS Test Account setup guide outdated recommendations

### ISSUE THREAD

**Issue by pwgr** [SwisscomTrustServices/pdfbox-ais#7]
The documentation at https://github.com/SwisscomTrustServices/pdfbox-ais-client/blob/main/docs/get-authentication-details.md#ais-test-account needs to be updated. It suggests to generate a 2048 bit key while apparently, starting from 2023, Swisscom requires certificates to be based on 3072 bit keys.

**Comment by ionut-vacariu-mindit** [comment]
@pwgr - Swisscom still support 2048 bit key, but recommend using of 3072 bit keys.
